CREATE MASKING POLICY CAPSTON.raw_data.EMAIL_MASK AS
(EMAIL VARCHAR) RETURNS VARCHAR ->
CASE WHEN CURRENT_ROLE = 'ADMIN' THEN EMAIL
ELSE REGEXP_REPLACE(EMAIL, '.+\@', '*****@')
END;
 
ALTER TABLE CAPSTON.raw_data.CUSTOMER_RAW MODIFY COLUMN email SET MASKING POLICY CAPSTON.raw_data.EMAIL_MASK;
 
 
CREATE MASKING POLICY CAPSTON.raw_data.Phone_MASK AS
(PHONE VARCHAR) RETURNS VARCHAR ->
CASE WHEN CURRENT_ROLE = 'ADMIN' THEN PHONE
ELSE SUBSTR(PHONE, 0, 5) || '***-****'
END;
 
 
ALTER TABLE CAPSTON.raw_data.CUSTOMER_RAW MODIFY COLUMN phone_number SET MASKING POLICY CAPSTON.raw_data.Phone_MASK;